-- MySQL Script generated by MySQL Workbench
-- Thu Oct 31 18:34:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbescola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbescola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbescola` DEFAULT CHARACTER SET utf8 ;
USE `dbescola` ;

-- -----------------------------------------------------
-- Table `dbescola`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbescola`.`aluno` (
  `aluno_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `curso` VARCHAR(100) NOT NULL,
  `nivel` VARCHAR(100) NOT NULL,
  `idade` INT NOT NULL,
  PRIMARY KEY (`aluno_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbescola`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbescola`.`turma` (
  `turma_id` INT NOT NULL AUTO_INCREMENT,
  `nometurma` VARCHAR(255) NOT NULL,
  `sala` VARCHAR(45) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`turma_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbescola`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbescola`.`matricula` (
  `matricula_id` INT NOT NULL AUTO_INCREMENT,
  `nota_1` FLOAT NULL,
  `nota_2` FLOAT NULL,
  `nota_3` FLOAT NULL,
  `nota_final` FLOAT NULL,
  `nr_faltas` INT NULL,
  `aluno_id` INT NOT NULL,
  `turma_id` INT NOT NULL,
  PRIMARY KEY (`matricula_id`),
  INDEX `fk_matricula_aluno_idx` (`aluno_id` ASC) VISIBLE,
  INDEX `fk_matricula_turma1_idx` (`turma_id` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_aluno`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `dbescola`.`aluno` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `dbescola`.`turma` (`turma_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ----------------------------------------------------------------------------------------------------------------------------------------------
-- MySQL Script generated by MySQL Workbench
-- Thu Oct 31 20:22:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BomGosto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BomGosto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BomGosto` DEFAULT CHARACTER SET utf8 ;
USE `BomGosto` ;

-- -----------------------------------------------------
-- Table `BomGosto`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BomGosto`.`comanda` (
  `comanda_id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `mesa` INT NOT NULL,
  `nomeCliente` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`comanda_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BomGosto`.`cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BomGosto`.`cardapio` (
  `cardapio_id` INT NOT NULL,
  `nomeCafe` VARCHAR(100) NOT NULL,
  `composicao` VARCHAR(255) NOT NULL,
  `valorUnitario` FLOAT NOT NULL,
  PRIMARY KEY (`cardapio_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BomGosto`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BomGosto`.`pedido` (
  `pedido_id` INT NOT NULL AUTO_INCREMENT,
  `cardapio_id` INT NOT NULL,
  `quantidade` INT NULL,
  `comanda_comanda_id` INT NOT NULL,
  PRIMARY KEY (`pedido_id`),
  INDEX `fk_pedido_cardapio_idx` (`cardapio_id` ASC) VISIBLE,
  INDEX `fk_pedido_comanda1_idx` (`comanda_comanda_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cardapio`
    FOREIGN KEY (`cardapio_id`)
    REFERENCES `BomGosto`.`cardapio` (`cardapio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_comanda1`
    FOREIGN KEY (`comanda_comanda_id`)
    REFERENCES `BomGosto`.`comanda` (`comanda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------------------------------------------------------------------------------------------------

-- MySQL Script generated by MySQL Workbench
-- Sat Nov  2 21:57:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escolaInformatica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escolaInformatica` DEFAULT CHARACTER SET utf8 ;
USE `escolaInformatica` ;

-- -----------------------------------------------------
-- Table `escolaInformatica`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolaInformatica`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `tipoCurso` VARCHAR(100) NOT NULL,
  `nomeCurso` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escolaInformatica`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolaInformatica`.`professor` (
  `idprofessor` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `titulacao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idprofessor`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escolaInformatica`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolaInformatica`.`aluno` (
  `idaluno` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT NOT NULL,
  `dataMatricula` DATE NOT NULL,
  `nomeAluno` VARCHAR(255) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `altura` FLOAT NOT NULL,
  `peso` FLOAT NOT NULL,
  PRIMARY KEY (`idaluno`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escolaInformatica`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolaInformatica`.`turma` (
  `idturma` INT NOT NULL AUTO_INCREMENT,
  `quantidadeAlunos` INT NOT NULL,
  `horarioAula` VARCHAR(100) NOT NULL,
  `duracaoAula` TIME NOT NULL,
  `dataInicial` DATE NOT NULL,
  `dataFinal` DATE NOT NULL,
  `curso_idcurso` INT NOT NULL,
  `professor_idprofessor` INT NOT NULL,
  `aluno_idalunoMonitor` INT NOT NULL,
  PRIMARY KEY (`idturma`),
  INDEX `fk_turma_curso1_idx` (`curso_idcurso` ASC) VISIBLE,
  INDEX `fk_turma_professor1_idx` (`professor_idprofessor` ASC) VISIBLE,
  INDEX `fk_turma_aluno1_idx` (`aluno_idalunoMonitor` ASC) VISIBLE,
  CONSTRAINT `fk_turma_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `escolaInformatica`.`curso` (`idcurso`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_professor1`
    FOREIGN KEY (`professor_idprofessor`)
    REFERENCES `escolaInformatica`.`professor` (`idprofessor`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_aluno1`
    FOREIGN KEY (`aluno_idalunoMonitor`)
    REFERENCES `escolaInformatica`.`aluno` (`idaluno`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escolaInformatica`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolaInformatica`.`telefone` (
  `idtelefone` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM("Residencial", "Celular", "Contato") NOT NULL,
  `numeroTelefone` VARCHAR(45) NOT NULL,
  `professor_idprofessor` INT NULL,
  `aluno_idaluno` INT NULL,
  PRIMARY KEY (`idtelefone`),
  INDEX `fk_telefone_professor1_idx` (`professor_idprofessor` ASC) VISIBLE,
  INDEX `fk_telefone_aluno1_idx` (`aluno_idaluno` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_professor1`
    FOREIGN KEY (`professor_idprofessor`)
    REFERENCES `escolaInformatica`.`professor` (`idprofessor`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefone_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `escolaInformatica`.`aluno` (`idaluno`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CHECK (`aluno_idaluno` IS NOT NULL OR `professor_idprofessor` IS NOT NULL))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escolaInformatica`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolaInformatica`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(20) NOT NULL,
  `rua` VARCHAR(255) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `aluno_idaluno` INT NULL,
  `professor_idprofessor` INT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Endereco_aluno1_idx` (`aluno_idaluno` ASC) VISIBLE,
  INDEX `fk_Endereco_professor1_idx` (`professor_idprofessor` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `escolaInformatica`.`aluno` (`idaluno`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_professor1`
    FOREIGN KEY (`professor_idprofessor`)
    REFERENCES `escolaInformatica`.`professor` (`idprofessor`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CHECK (`aluno_idaluno` IS NOT NULL OR `professor_idprofessor` IS NOT NULL))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escolaInformatica`.`ausencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolaInformatica`.`ausencia` (
  `idausencia` INT NOT NULL,
  `dataAusencia` DATE NOT NULL,
  `aluno_idaluno` INT NOT NULL,
  PRIMARY KEY (`idausencia`),
  INDEX `fk_ausencia_aluno1_idx` (`aluno_idaluno` ASC) VISIBLE,
  CONSTRAINT `fk_ausencia_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `escolaInformatica`.`aluno` (`idaluno`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escolaInformatica`.`aluno_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolaInformatica`.`aluno_turma` (
  `aluno_idaluno` INT NOT NULL,
  `turma_idturma` INT NOT NULL,
  PRIMARY KEY (`aluno_idaluno`, `turma_idturma`),
  INDEX `fk_aluno_has_turma_turma1_idx` (`turma_idturma` ASC) VISIBLE,
  INDEX `fk_aluno_has_turma_aluno_idx` (`aluno_idaluno` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_turma_aluno`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `escolaInformatica`.`aluno` (`idaluno`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_turma_turma1`
    FOREIGN KEY (`turma_idturma`)
    REFERENCES `escolaInformatica`.`turma` (`idturma`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

